---
  - name: copy nginx config
    copy:
      src: nginx/training_nginx.conf
      dest: "{{nginx_conf}}/"
  - name: check if default conf exists
    stat: 
      path: "{{nginx_conf}}/default.conf"
    register: default_conf
  - name: deactivate default conf in conf.d/
    command: mv "{{nginx_conf}}/default.conf" "{{nginx_conf}}/default.deactivated"
    when: default_conf.stat.exists
  - name: copy hey page
    copy:
      src: nginx/hey.html
      dest: "{{index_root}}/"
  - name: start nginx
    service:
      name: nginx
      state: started