version: '3.3'
services:
  nginx:
    image: nginx
    ports: 
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./hey.html:/var/www/html/hey.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
      - ./ssl/:/etc/ssl/

  wordpress:
    image: wordpress:php8.2-fpm-alpine
    depends_on:
      - wordpress_db
    ports:
      - 9000:9000
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 0
    volumes:
      - ./html:/var/www/html

  wordpress_db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_HOST: wordpress_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    depends_on:
      - wordpress_db
    image: phpmyadmin/phpmyadmin
    # Uncomment to have access to db manager
    ports:
      - 8181:8181
    restart: always
    environment:
      MYSQL_HOST: wordpress_db
      PMA_HOST: wordpress_db
      MYSQL_ROOT_PASSWORD: examplepass
      APACHE_PORT: 8181

  setup:
    image: alpine
    depends_on:
      - wordpress_db
    volumes:
      - ./wordpressdb.sql:/tmp/wordpressdb.sql
    command: sh -c "apk add mysql-client && sleep 30 && mysql -u root --password=password -h wordpress_db wordpress < /tmp/wordpressdb.sql"

volumes:
  db_data: