version: '3.3'
services:
  nginx:
    image: nginx
    ports: 
      - 80:80
    restart: always
    volumes:
      - ../files/hey.html:/var/www/html/hey.html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  wordpress:
    image: wordpress
    depends_on:
      - wordpress_db
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 0
    volumes:
      - ../files/html:/var/www/html

  wordpress_db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_HOST: wordpress_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    depends_on:
      - wordpress_db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      MYSQL_HOST: wordpress_db
      PMA_HOST: wordpress_db
      MYSQL_ROOT_PASSWORD: examplepass

  setup:
    image: alpine
    depends_on:
      - wordpress_db
    volumes:
      - ../files/wordpressdb.sql:/tmp/wordpressdb.sql
    command: sh -c "apk add mysql-client && sleep 30 && mysql -u root --password=password -h wordpress_db wordpress < /tmp/wordpressdb.sql"

volumes:
  db_data: