  - name: Ensure Docker is installed
    package:
      name: docker.io
      state: present

  - name: Ensure Docker Compose is installed
    package:
      name: docker-compose
      state: present

  - name: Create working directory
    file:
      path: /home/wordpress-compose
      state: directory

  - name: Copy docker-compose.yaml to the target host
    copy:
      src: ./templates/docker-compose.yaml
      dest: /home/wordpress-compose/docker-compose.yaml

  - name: Copy base files
    synchronize:
      src: files/
      dest: /home/wordpress-compose/

  - name: Ensure WordPress containers are running
    docker_compose:
      project_src: /home/wordpress-compose
      state: present
      restarted: yes
