  - name: Render nginx conf template
    template:
      src: ./default.conf.j2
      dest: /home/wordpress-compose/default.conf

  - name: Render nginx conf template
    template:
      src: ./docker-compose.yaml.j2
      dest: /home/wordpress-compose/docker-compose.yaml

  - name: Copy base files
    synchronize:
      src: files/
      dest: /home/wordpress-compose/

  - name: Ensure WordPress containers are running
    docker_compose:
      project_src: /home/wordpress-compose
      state: present
      restarted: yes