  - name: Print host name
    debug:
      msg: Target host is {{ ansible_host }}

  - name: Ensure Docker is installed
    package:
      name: docker.io
      state: present

  - name: Ensure Docker Compose is installed
    package:
      name: docker-compose
      state: present

  - name: Create working directory
    file:
      path: /home/wordpress-compose
      state: directory