version: '3'
services:
  wordpress:
    image: wordpress
    depends_on:
      - wordpress_db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  wordpress_db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  phpmyadmin:
    depends_on:
      - wordpress_db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      PMA_HOST: wordpress_db
      MYSQL_ROOT_PASSWORD: examplepass

networks:
  wpsite:

volumes:
  db_data:
