---
- name: Check docker script install
  stat:
    path: /home/user42/{{ docker_version }}.sh
  register: docker

- name: Uninstall previous docker installations
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: docker.stat.exists == false

- name: Download docker script install
  get_url:
    url: https://releases.rancher.com/install-docker/{{ docker_version }}.sh
    dest: /home/user42/{{ docker_version }}.sh
  when: docker.stat.exists == false

- name: Run docker script install
  shell:
    cmd: sh /home/user42/{{ docker_version }}.sh
  when: docker.stat.exists == false

- name: Install docker-compose
  apt:
    pkg: docker-compose
    state: present

- name: Install pip
  apt:
    pkg: python3-pip

- name: Install Docker SDK
  pip:
    name: dock
