---
- name: Configure /etc/hosts
  blockinfile:
    state: present
    dest: /etc/hosts
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK #"
    block: |
      {{ ip }}        {{ domain }}        {{ host }}
      127.0.0.1       local.localdomain   localhost
